import test from 'node:test';
import assert from 'node:assert/strict';
import { amount, initialLedger, normalizeExpense, normalizeExchange, normalizeTransfer, cashRemaining, summarize } from './model.js';
const draft = (extra = {}) => ({ title: '숙소', date: '2027-03-04', category: '숙소', status: 'paid', amount: '200000', currency: 'KRW', krw: '', payer: 'p1', method: 'card', exchangeId: '', members: ['p1', 'p2'], split: 'equal', custom: {}, note: '', ...extra });
const fx = ledger => normalizeExchange({ date: '2027-03-04', owner: 'p1', currency: 'VND', foreign: '5000000', krw: '300000', note: '' }, ledger);
test('200,000 hotel plus 60,000 meal settles with 70,000 from second person', () => {
 const l = initialLedger(true); l.expenses = [normalizeExpense(draft(), l), normalizeExpense(draft({ amount: '60000', payer: 'p2', category: '식비' }), l)];
 const s = summarize(l); assert.equal(s.paid, 260000); assert.deepEqual(s.settlements, [{ from: 'p2', to: 'p1', krw: 70000 }]);
 l.transfers.push(normalizeTransfer({ date: '2027-03-04', from: 'p2', to: 'p1', krw: '30000', note: '' }, l)); assert.equal(summarize(l).settlements[0].krw, 40000);
 l.transfers.push(normalizeTransfer({ date: '2027-03-04', from: 'p2', to: 'p1', krw: '40000', note: '' }, l)); assert.deepEqual(summarize(l).settlements, []);
});
test('planned expenses affect budget but not settlement', () => { const l = initialLedger(true); l.budget = 300000; l.expenses = [normalizeExpense(draft({ status: 'planned' }), l)]; const s = summarize(l); assert.equal(s.paid, 0); assert.equal(s.planned, 200000); assert.equal(s.remaining, 100000); assert.deepEqual(s.settlements, []); });
test('personal expenses and custom allocation preserve exact burden', () => { const l = initialLedger(true); l.expenses = [normalizeExpense(draft({ members: ['p1'] }), l)]; assert.deepEqual(summarize(l).settlements, []); l.expenses = [normalizeExpense(draft({ split: 'custom', custom: { p1: '150000', p2: '50000' } }), l)]; assert.equal(summarize(l).settlements[0].krw, 50000); assert.throws(() => normalizeExpense(draft({ split: 'custom', custom: { p1: '1', p2: '2' } }), l), /합계/); });
test('three-way split allocates integer remainder without losing money', () => { const l = initialLedger(true); l.people.push({ id: 'p3', name: '추가' }); const e = normalizeExpense(draft({ amount: '100', members: ['p1', 'p2', 'p3'] }), l); assert.deepEqual(e.shares, { p1: 34, p2: 33, p3: 33 }); l.expenses = [e]; assert.equal(summarize(l).rows.reduce((sum, p) => sum + p.balance, 0), 0); });
test('FX principal excluded, linked spending charged to funder, pending leaves cash intact', () => { const l = initialLedger(true); const x = fx(l); l.exchanges = [x]; assert.equal(summarize(l).paid, 0); const input = draft({ currency: 'VND', amount: '500000', krw: '30000', exchangeId: x.id, method: 'cash', payer: 'p2' }); l.expenses = [normalizeExpense(input, l), normalizeExpense({ ...input, status: 'planned' }, l)]; assert.equal(l.expenses[0].payer, 'p1'); assert.equal(summarize(l).paid, 30000); assert.equal(cashRemaining(l, x), 4500000); assert.equal(summarize(l).settlements[0].krw, 15000); });
test('cash overspend blocked and editing excludes existing expense', () => { const l = initialLedger(true); const x = fx(l); l.exchanges = [x]; const input = draft({ currency: 'VND', amount: '5000000', krw: '300000', exchangeId: x.id, method: 'cash' }); const e = normalizeExpense(input, l); l.expenses = [e]; assert.throws(() => normalizeExpense(input, l), /남은 현금/); assert.doesNotThrow(() => normalizeExpense({ ...input, id: e.id }, l)); assert.throws(() => normalizeExchange(x, l), /연결된 지출/); });
test('currency precision is validated; decimal USD cash balances are exact', () => { assert.throws(() => amount('1.5', 'VND')); assert.throws(() => amount('1.001', 'USD')); assert.throws(() => amount('-1')); const l = initialLedger(true); const x = normalizeExchange({ date: '2027-03-04', owner: 'p1', currency: 'USD', foreign: '0.30', krw: '420', note: '' }, l); l.exchanges=[x]; l.expenses=[normalizeExpense(draft({ currency:'USD', amount:'0.1', krw:'140', method:'cash', exchangeId:x.id }),l)]; assert.equal(cashRemaining(l,x),0.2); });
test('invalid participants, blank titles, dates and empty split are rejected', () => { const l = initialLedger(true); for (const extra of [{ title: ' ' }, { payer: 'missing' }, { date: '2027-02-30' }, { members: [] }]) assert.throws(() => normalizeExpense(draft(extra), l)); assert.throws(() => normalizeTransfer({ date: '2027-03-04', from: 'p1', to: 'p1', krw: '100', note: '' }, l)); });
test('overpayment reverses settlement direction and removing an expense recalculates', () => { const l = initialLedger(true); l.expenses = [normalizeExpense(draft(), l)]; l.transfers = [normalizeTransfer({ date: '2027-03-04', from: 'p2', to: 'p1', krw: '120000', note: '' }, l)]; assert.deepEqual(summarize(l).settlements, [{ from: 'p1', to: 'p2', krw: 20000 }]); l.expenses = []; assert.equal(summarize(l).settlements[0].krw, 120000); });
